### ISSUE TITLE
Onboarding checklist

### ISSUE THREAD

**Issue by mathewtrivett** [WeAreSnook/developer-manual#7]
> As a someone onboarding a developer to Snook, I need a checklist to be confident that I've covered everything I need to.

## Acceptance criteria

- [x] It should include a checklist for how to securely add someone to Github
- [x] It should include a checklist for when and how to add someone to Heroku
- [x] It should include a guide / checklist for how we currently use Netlify for static sites
- [x] It should include a guide / principles for managing secrets on projects #10 
- [x] It should have a checklist / guide to set up a laptop for typical development 
- [x] It should include a background reading list
- [x] It understand the GDS Service standard and how Snook applies it
- [x] It understand what [12 Factor app principles](https://12factor.net/) are
- [x] It understand the principles of the Agile manifesto
- [x] It should include other recommended reading
- [x] I should be able to understand who does what in the build team and who to turn to for what.
- [x] I should get a good understanding of our principles and ways of working

## Links

- Thoughtbot have a [laptop](https://github.com/thoughtbot/laptop) script that developers can use to set up and configure a new Macbook with their tools.
- Maybe a video on the Agile principles is easier to understand? https://www.youtube.com/watch?v=LMnozmayNJQ

**Comment by tosbourn** [comment]
Potential additional acceptance criteria:

- background reading for the first few days/weeks, e.g the [GDS service standard](https://www.gov.uk/service-manual/service-standard) helps set the tone for some of the terms and practices. Other topics could be TDD, 12 Factor App, Agile Manifesto. This makes sure we're on the same baseline
- team orientation - [the build team slides](https://docs.google.com/presentation/d/1uKBzy72C60IAsEYdY20Ut_S-1e7M16yppniyx2BsTKg/edit#slide=id.g980747369b_1_0) and related "who does what" type stuff. This makes sure we know who to ask questions to.
